### ISSUE TITLE
OpenCV 4.0 not supported

### ISSUE THREAD

**Issue by marcigarza** [ceccocats/tkDNN#1]
/home/nvidia/tkDNN/demo/detection/detection.cpp: In function ‘int main(int, char**)’:
/home/nvidia/tkDNN/demo/detection/detection.cpp:163:54: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope
         cv::Mat img = cv::imread(image_path.c_str(), CV_LOAD_IMAGE_COLOR);

The solution to this error is to change CV_LOAD_IMAGE_COLOR for cv::IMREAD_COLOR.

Since opencv 4.0 the macros have changed.

**Comment by ceccocats** [comment]
Now opencv 4 is supported
