### ISSUE TITLE
Is it possible that tkDNN compatible with c++17?

### ISSUE THREAD

**Issue by mochechan** [ceccocats/tkDNN#105]
Is it possible that tkDNN compatible with c++17?

**Comment by ceccocats** [comment]
I mochechan, 
tkDNN require at least c++11, I personally never used c++17 but I think is retrocompatibile, maybe you will get some warning.
Just try to modify the cmakelists.txt and compile

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
