### ISSUE TITLE
export weights fork seems to be down

### ISSUE THREAD

**Issue by xixolio** [ceccocats/tkDNN#106]
Hi, thanks for your contribution! I want to export my darknet weights to the layer debug format. However, I haven't been able to access https://git.hipert.unimore.it/fgatti/darknet.git. Anyone else experiencing this problem? Is there another way to export the weights?  Or  could someone reupload the code ? 
Thanks in advance.

**Comment by Kuluum** [comment]
@xixolio It's up now

**Comment by Kuluum** [comment]
@ceccocats As I understand it is your repo. Maybe it's a good idea to make a fork on github to prevent such problems?

**Comment by ceccocats** [comment]
We had a service error for 1 week, I'm sorry for that.
