### ISSUE TITLE
Have example of image_list.txt and label_list.txt?

### ISSUE THREAD

**Issue by georgetseng1128** [ceccocats/tkDNN#11]
Hi, we try TKDNN_MODE=INT8, and setting have:

```
export TKDNN_CALIB_IMG_PATH=/path/to/calibration/image_list.txt
export TKDNN_CALIB_LABEL_PATH=/path/to/calibration/label_list.txt
```

Do you have example of image_list.txt and label_list.txt?

**Comment by mive93** [comment]
Hi, 

from the tkDNN folder run 
```
bash scripts/download_validation.sh COCO
```
It automatically downloads COCO2017 validation and creates image and label lists.

**Comment by georgetseng1128** [comment]
OK, We can success run INT8 mode, thank!
