### ISSUE TITLE
Bouding boxes coords

### ISSUE THREAD

**Issue by rafoliveira** [ceccocats/tkDNN#113]
Having a hard time understanding the code since I am not very experienced with C++
Which variable describes the coordinates of the bounding boxes?
I wanted to use them to make calculations

**Comment by rafoliveira** [comment]
Found it on this [file](https://github.com/ceccocats/tkDNN/blob/master/src/Yolo3Detection.cpp), described by the _res_ variable

**Comment by mive93** [comment]
Hi @rafoliveira 
Sorry, I missed the issue. 
The boxes are stored as tk::dnn::box (defined here https://github.com/ceccocats/tkDNN/blob/master/include/tkDNN/Layer.h#L577 )
```
struct box {
    int cl;
    float x, y, w, h;
    float prob;
    std::vector<float> probs;

    void print() 
    {
        std::cout<<"x: "<<x<<"\ty: "<<y<<"\tw: "<<w<<"\th: "<<h<<"\tcl: "<<cl<<"\tprob: "<<prob<<std::endl;
    }
};
```
For each detector, they are stored in batchDetected (https://github.com/ceccocats/tkDNN/blob/master/include/tkDNN/DetectionNN.h#L71)

**Comment by sharoseali** [comment]
HI! I tested both  FP32 and FP16 implementation with batch size = 4 but when I run the test I get this result, Can anyone help. I think it's an NMS problem but don't know how to fix it.
![Screenshot from 2021-01-05 23-57-32](https://user-images.githubusercontent.com/19869426/104244098-d1ee6a80-5472-11eb-8556-76731051a30c.png)

**Comment by sharoseali** [comment]
> HI! I tested both FP32 and FP16 implementation with batch size = 4 but when I run the test I get this result as seen below. Every object is surrounded by 4 bounding boxes., Can anyone help? I think it's an NMS problem but don't know how to fix it.
> ![Screenshot from 2021-01-05 23-57-32](https://user-images.githubusercontent.com/19869426/104244098-d1ee6a80-5472-11eb-8556-76731051a30c.png)
> Thank You

@mive93

**Comment by mive93** [comment]
Hi @sharoseali 

what are you using? Which platform?
I never had that problem. 
Just run a bunch of models and everything is fine for me.

**Comment by sharoseali** [comment]
> Hi @sharoseali
> 
> what are you using? Which platform?
> I never had that problem.
> Just run a bunch of models and everything is fine for me.

İ am running my custom trained yolo v4  on AGX xavier using your repo. When İ use batch size equals 1 .. its fine, but when i use batch size equals 4 then on display i see 4 bounding boxes running with each moving object as İ show above. What the thing come in mind is that its issue in NMS.. and bounding boxes are 4 times drawn .Also FPS get very less when i run with batch size equals 4. thanks for replying
