### ISSUE TITLE
CPU RAM fails

### ISSUE THREAD

**Issue by beybars1** [ceccocats/tkDNN#116]
Hi man, I would like to thank you for the work provided. I am running my Jetson nano and facing the CPU RAM failing when process this command: **./darknet export <path-to-cfg-file> <path-to-weights> layers**. 
I did not update the Makefile in the darknet folder of this repository (https://git.hipert.unimore.it/fgatti/darknet), so that it is made with GPU=0, OPENCV=0 etc. I just cannot export darknet weights. 

please, help.

**Comment by ceccocats** [comment]
Can darknet run the network on Jetson Nano?
If you not have enough memory you can't run it

**Comment by Mattis95** [comment]
What .cfg file are you using? Try to set batch = 1 in the .cfg file.

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
