### ISSUE TITLE
Yolov4tiny engine build error

### ISSUE THREAD

**Issue by ahmedius2** [ceccocats/tkDNN#118]
Hi! Firstly, thanks for sharing this nice project with us.

I am trying to run YOLOv4-tiny on NVDLA of Jetson AGX. Since leaky relu and mish activations are not supported on NVDLA, I changed all leaky and mish layers into relu in the darknet .cfg files, like this:
activation=leaky --> activation=relu
activation=mish --> activation=relu
For the YOLOv4, YOLOv3, and YOLOv3-tiny, it builds the CUDA engine and serialize it without any problem and all activation layers become supported on DLA. However, the engine does not build on YOLOv4-tiny, the program aborts by saying could not build the engine. What could be the reason for this?

Best regards,

Ahmet Soyyigit

**Comment by mive93** [comment]
Hi @ahmedius2 

It's indeed weird, could you please activate the debug (check [README](https://github.com/ceccocats/tkDNN#run-the-demo) ) and copy here the output please?

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
