### ISSUE TITLE
use yolo4tiny in jetson nano only have 4 FPS

### ISSUE THREAD

**Issue by arnode** [ceccocats/tkDNN#121]
use yolo4tiny in jetson nano only have 4 FPS

**Comment by mive93** [comment]
It sounds weird to me.
Those are my results on Jetson Nano, Jetpack 4.4 on average 5k images, for yolov4tiny with input size 512x512, taking into account preprocessing, inference and postprocessing:

```
			AVG FPS		MAX FPS		MIN FPS
fp32	yolo4tiny512	19.18		20.09		12.57
fp16	yolo4tiny512	26.49		28.01		18.39

```

Have you launched jetson_clock?

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
