### ISSUE TITLE
I want to use tkDNN on darknet_ros.

### ISSUE THREAD

**Issue by Hiroaki-K4** [ceccocats/tkDNN#124]
Hi.
Thank you for your work!
I want to use tkDNN on darknet_ros.
https://github.com/leggedrobotics/darknet_ros
If I want to run tkDNN on darknet_ros, where should I change it?

**Comment by jaronski** [comment]
same here!

**Comment by Hiroaki-K4** [comment]
@jaronski 
I made tkdnn_ros. I just made it possible to run tkDNN on ROS.
https://github.com/Hiroaki-K4/tkdnn_ros

**Comment by Hiroaki-K4** [comment]
@jaronski 
I made tkdnn_ros private. Because I didn't get permission from the CTO of my company. If I get permission to publish, make it public again.

**Comment by jaronski** [comment]
Too bad 😭

Jaron Martinez

On 21. Oct 2020, at 10:44, Hiroaki-K4 <notifications@github.com> wrote:

﻿
@jaronski
I made tkdnn_ros private. Because I didn't get permission from the CTO of my company. If I get permission to publish, make it public again.

**Comment by Hiroaki-K4** [comment]
I’m sorry. If I get permission to publish, I will report it to you here.

**Comment by garyzf** [comment]
https://github.com/garyzf/tkdnn_ros.git, try it
