### ISSUE TITLE
How to release the memory when my program running for a long time?

### ISSUE THREAD

**Issue by sjtuzbk** [ceccocats/tkDNN#135]
I noticed that the DetectionNN class has some member variables of vector class:
```
std::vector<tk::dnn::box> detected; /*bounding boxes in output*/
std::vector<std::vector<tk::dnn::box>> batchDetected; /*bounding boxes in output*/
std::vector<double> stats; /*keeps track of inference times (ms)*/
std::vector<std::string> classesNames;
```
Therefore,  as the program runs, the memory occupied by vectors will increase. If my program runs for a long time, the memory will eventually be insufficient. So how to release the memory?

Looking forward to your reply!

**Comment by mive93** [comment]
Hi @sjtuzbk 
Every new inference [detected](https://github.com/ceccocats/tkDNN/blob/f778e1aa998f894654b24c0ab9ad759c0eb14019/src/Yolo3Detection.cpp#L110) and [batchDetected](https://github.com/ceccocats/tkDNN/blob/master/include/tkDNN/DetectionNN.h#L133) are cleaned, while classesNames never changes. 
The only one is stats, that saves a double for each inference to track the performance. That is true, it should be cleaned time to times.

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
