### ISSUE TITLE
Classification Models

### ISSUE THREAD

**Issue by RoudyT** [ceccocats/tkDNN#137]
Hello, thank you for this amazing library.

Can this library be used for simple image classification models?
If not, can you please add this feature to this library?

Best,

Roudy

**Comment by mive93** [comment]
Hi @RoudyT 
yes, it can be used. This library is a framework for general DNNs. There are mainly detectors (yolo, centernet, mobilenetv2ssd), but also semantic segmentation networks (branch segmentation) and regression DNN (imuodom). 
For now, we don't plan to port any classification network.

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
