### ISSUE TITLE
Semantic Segmentation Examples

### ISSUE THREAD

**Issue by jawadbh** [ceccocats/tkDNN#138]
Hello,
Can you guide me to a semantic segmentation example that uses this repo?

**Comment by mive93** [comment]
Hi @jawadbh 
I will soon merge the semantic segmentation branch and write a README for that. 
As of now, you should checkout the segmentation branch, run test_shelfnet and then use the rt produces in the seg_demo.

**Comment by mive93** [comment]
Here's the readme for the segmentation stuff: https://github.com/ceccocats/tkDNN/blob/segmentation/README_seg.md

Soon we'll merge it with the master.

**Comment by MI-LA01** [comment]
Just to know, did you finally merged on trunk?

**Comment by mive93** [comment]
@MI-LA01 just did it.
