### ISSUE TITLE
Using tkDNN as a plugin in software with other license.

### ISSUE THREAD

**Issue by Szamtu** [ceccocats/tkDNN#142]
Good morning,

Is it possible to use tkDNN library (on GPL license) as a plugin in other open source project, as a self plugin?

I'm asking, becouse, I could add a tkDNN plugin to a fork of project, that we sometimes update.
The project: [PastaPi](https://github.com/Szamtu/pastaPi)  is under MIT license (as original project [Spaghetti](https://github.com/aljen/spaghetti) forked from).

My idea is to add plugin element called tkDNN_yolo that is linked dynamicly with the tkDNN library. Separate plugin with it's own cmake could be licensed under GPL. (the plugin that can be turned on/off to build with the project). Is such plugin compatybile with tkDNN GPLv2 license?

**Comment by ceccocats** [comment]
I think is ok, as far you keep the license.
But honestly... I'm not a lawyer

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
