### ISSUE TITLE
Could not build cuda engine

### ISSUE THREAD

**Issue by panca1** [ceccocats/tkDNN#143]
Hi everybody. 
I have an error when I run ./test_yolo4. Here is the code:

`Not supported field: batch=1
Not supported field: subdivisions=1
Not supported field: momentum=0.949
Not supported field: decay=0.0005
Not supported field: angle=0
Not supported field: saturation = 1.5
Not supported field: exposure = 1.5
Not supported field: hue=.1
Not supported field: learning_rate=0.00261
Not supported field: burn_in=1000
Not supported field: max_batches = 500500
Not supported field: policy=steps
Not supported field: steps=400000,450000
Not supported field: scales=.1,.1
Not supported field: mosaic=1
New NETWORK (tkDNN v0.5, CUDNN v8.004)
Reading weights: I=3 O=32 KERNEL=3x3x1
Reading weights: I=32 O=64 KERNEL=3x3x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=64 O=32 KERNEL=1x1x1
Reading weights: I=32 O=64 KERNEL=3x3x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=128 O=64 KERNEL=1x1x1
Reading weights: I=64 O=128 KERNEL=3x3x1
Reading weights: I=128 O=64 KERNEL=1x1x1
Reading weights: I=128 O=64 KERNEL=1x1x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=64 O=64 KERNEL=3x3x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=64 O=64 KERNEL=3x3x1
Reading weights: I=64 O=64 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=256 KERNEL=3x3x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=128 O=128 KERNEL=3x3x1
Reading weights: I=128 O=128 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=256 O=256 KERNEL=3x3x1
Reading weights: I=256 O=256 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=3x3x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=3x3x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=3x3x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=512 O=512 KERNEL=3x3x1
Reading weights: I=512 O=512 KERNEL=1x1x1
Reading weights: I=1024 O=1024 KERNEL=1x1x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=2048 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=128 O=256 KERNEL=3x3x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=128 O=256 KERNEL=3x3x1
Reading weights: I=256 O=128 KERNEL=1x1x1
Reading weights: I=128 O=256 KERNEL=3x3x1
Reading weights: I=256 O=255 KERNEL=1x1x1
Not supported field: anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
Not supported field: jitter=.3
Not supported field: ignore_thresh = .7
Not supported field: truth_thresh = 1
Not supported field: iou_thresh=0.213
Not supported field: cls_normalizer=1.0
Not supported field: iou_normalizer=0.07
Not supported field: iou_loss=ciou
Not supported field: nms_kind=greedynms
Not supported field: beta_nms=0.6
Reading weights: I=128 O=256 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=256 KERNEL=1x1x1
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=512 O=255 KERNEL=1x1x1
Not supported field: anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
Not supported field: jitter=.3
Not supported field: ignore_thresh = .7
Not supported field: truth_thresh = 1
Not supported field: iou_thresh=0.213
Not supported field: cls_normalizer=1.0
Not supported field: iou_normalizer=0.07
Not supported field: iou_loss=ciou
Not supported field: nms_kind=greedynms
Not supported field: beta_nms=0.6
Reading weights: I=256 O=512 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=512 KERNEL=1x1x1
Reading weights: I=512 O=1024 KERNEL=3x3x1
Reading weights: I=1024 O=255 KERNEL=1x1x1
Not supported field: anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
Not supported field: jitter=.3
Not supported field: ignore_thresh = .7
Not supported field: truth_thresh = 1
Not supported field: random=1
Not supported field: iou_thresh=0.213
Not supported field: cls_normalizer=1.0
Not supported field: iou_normalizer=0.07
Not supported field: iou_loss=ciou
Not supported field: nms_kind=greedynms
Not supported field: beta_nms=0.6

====================== NETWORK MODEL ======================
N.  Layer type       input (H*W,CH)        output (H*W,CH) 
  0 Conv2d           416 x  416,    3  ->  416 x  416,   32
  1 ActivationMish   416 x  416,   32  ->  416 x  416,   32
  2 Conv2d           416 x  416,   32  ->  208 x  208,   64
  3 ActivationMish   208 x  208,   64  ->  208 x  208,   64
  4 Conv2d           208 x  208,   64  ->  208 x  208,   64
  5 ActivationMish   208 x  208,   64  ->  208 x  208,   64
  6 Route            208 x  208,   64  ->  208 x  208,   64
  7 Conv2d           208 x  208,   64  ->  208 x  208,   64
  8 ActivationMish   208 x  208,   64  ->  208 x  208,   64
  9 Conv2d           208 x  208,   64  ->  208 x  208,   32
 10 ActivationMish   208 x  208,   32  ->  208 x  208,   32
 11 Conv2d           208 x  208,   32  ->  208 x  208,   64
 12 ActivationMish   208 x  208,   64  ->  208 x  208,   64
 13 Shortcut         208 x  208,   64  ->  208 x  208,   64
 14 Conv2d           208 x  208,   64  ->  208 x  208,   64
 15 ActivationMish   208 x  208,   64  ->  208 x  208,   64
 16 Route            208 x  208,  128  ->  208 x  208,  128
 17 Conv2d           208 x  208,  128  ->  208 x  208,   64
 18 ActivationMish   208 x  208,   64  ->  208 x  208,   64
 19 Conv2d           208 x  208,   64  ->  104 x  104,  128
 20 ActivationMish   104 x  104,  128  ->  104 x  104,  128
 21 Conv2d           104 x  104,  128  ->  104 x  104,   64
 22 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 23 Route            104 x  104,  128  ->  104 x  104,  128
 24 Conv2d           104 x  104,  128  ->  104 x  104,   64
 25 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 26 Conv2d           104 x  104,   64  ->  104 x  104,   64
 27 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 28 Conv2d           104 x  104,   64  ->  104 x  104,   64
 29 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 30 Shortcut         104 x  104,   64  ->  104 x  104,   64
 31 Conv2d           104 x  104,   64  ->  104 x  104,   64
 32 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 33 Conv2d           104 x  104,   64  ->  104 x  104,   64
 34 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 35 Shortcut         104 x  104,   64  ->  104 x  104,   64
 36 Conv2d           104 x  104,   64  ->  104 x  104,   64
 37 ActivationMish   104 x  104,   64  ->  104 x  104,   64
 38 Route            104 x  104,  128  ->  104 x  104,  128
 39 Conv2d           104 x  104,  128  ->  104 x  104,  128
 40 ActivationMish   104 x  104,  128  ->  104 x  104,  128
 41 Conv2d           104 x  104,  128  ->   52 x   52,  256
 42 ActivationMish    52 x   52,  256  ->   52 x   52,  256
 43 Conv2d            52 x   52,  256  ->   52 x   52,  128
 44 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 45 Route             52 x   52,  256  ->   52 x   52,  256
 46 Conv2d            52 x   52,  256  ->   52 x   52,  128
 47 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 48 Conv2d            52 x   52,  128  ->   52 x   52,  128
 49 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 50 Conv2d            52 x   52,  128  ->   52 x   52,  128
 51 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 52 Shortcut          52 x   52,  128  ->   52 x   52,  128
 53 Conv2d            52 x   52,  128  ->   52 x   52,  128
 54 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 55 Conv2d            52 x   52,  128  ->   52 x   52,  128
 56 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 57 Shortcut          52 x   52,  128  ->   52 x   52,  128
 58 Conv2d            52 x   52,  128  ->   52 x   52,  128
 59 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 60 Conv2d            52 x   52,  128  ->   52 x   52,  128
 61 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 62 Shortcut          52 x   52,  128  ->   52 x   52,  128
 63 Conv2d            52 x   52,  128  ->   52 x   52,  128
 64 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 65 Conv2d            52 x   52,  128  ->   52 x   52,  128
 66 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 67 Shortcut          52 x   52,  128  ->   52 x   52,  128
 68 Conv2d            52 x   52,  128  ->   52 x   52,  128
 69 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 70 Conv2d            52 x   52,  128  ->   52 x   52,  128
 71 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 72 Shortcut          52 x   52,  128  ->   52 x   52,  128
 73 Conv2d            52 x   52,  128  ->   52 x   52,  128
 74 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 75 Conv2d            52 x   52,  128  ->   52 x   52,  128
 76 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 77 Shortcut          52 x   52,  128  ->   52 x   52,  128
 78 Conv2d            52 x   52,  128  ->   52 x   52,  128
 79 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 80 Conv2d            52 x   52,  128  ->   52 x   52,  128
 81 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 82 Shortcut          52 x   52,  128  ->   52 x   52,  128
 83 Conv2d            52 x   52,  128  ->   52 x   52,  128
 84 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 85 Conv2d            52 x   52,  128  ->   52 x   52,  128
 86 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 87 Shortcut          52 x   52,  128  ->   52 x   52,  128
 88 Conv2d            52 x   52,  128  ->   52 x   52,  128
 89 ActivationMish    52 x   52,  128  ->   52 x   52,  128
 90 Route             52 x   52,  256  ->   52 x   52,  256
 91 Conv2d            52 x   52,  256  ->   52 x   52,  256
 92 ActivationMish    52 x   52,  256  ->   52 x   52,  256
 93 Conv2d            52 x   52,  256  ->   26 x   26,  512
 94 ActivationMish    26 x   26,  512  ->   26 x   26,  512
 95 Conv2d            26 x   26,  512  ->   26 x   26,  256
 96 ActivationMish    26 x   26,  256  ->   26 x   26,  256
 97 Route             26 x   26,  512  ->   26 x   26,  512
 98 Conv2d            26 x   26,  512  ->   26 x   26,  256
 99 ActivationMish    26 x   26,  256  ->   26 x   26,  256
100 Conv2d            26 x   26,  256  ->   26 x   26,  256
101 ActivationMish    26 x   26,  256  ->   26 x   26,  256
102 Conv2d            26 x   26,  256  ->   26 x   26,  256
103 ActivationMish    26 x   26,  256  ->   26 x   26,  256
104 Shortcut          26 x   26,  256  ->   26 x   26,  256
105 Conv2d            26 x   26,  256  ->   26 x   26,  256
106 ActivationMish    26 x   26,  256  ->   26 x   26,  256
107 Conv2d            26 x   26,  256  ->   26 x   26,  256
108 ActivationMish    26 x   26,  256  ->   26 x   26,  256
109 Shortcut          26 x   26,  256  ->   26 x   26,  256
110 Conv2d            26 x   26,  256  ->   26 x   26,  256
111 ActivationMish    26 x   26,  256  ->   26 x   26,  256
112 Conv2d            26 x   26,  256  ->   26 x   26,  256
113 ActivationMish    26 x   26,  256  ->   26 x   26,  256
114 Shortcut          26 x   26,  256  ->   26 x   26,  256
115 Conv2d            26 x   26,  256  ->   26 x   26,  256
116 ActivationMish    26 x   26,  256  ->   26 x   26,  256
117 Conv2d            26 x   26,  256  ->   26 x   26,  256
118 ActivationMish    26 x   26,  256  ->   26 x   26,  256
119 Shortcut          26 x   26,  256  ->   26 x   26,  256
120 Conv2d            26 x   26,  256  ->   26 x   26,  256
121 ActivationMish    26 x   26,  256  ->   26 x   26,  256
122 Conv2d            26 x   26,  256  ->   26 x   26,  256
123 ActivationMish    26 x   26,  256  ->   26 x   26,  256
124 Shortcut          26 x   26,  256  ->   26 x   26,  256
125 Conv2d            26 x   26,  256  ->   26 x   26,  256
126 ActivationMish    26 x   26,  256  ->   26 x   26,  256
127 Conv2d            26 x   26,  256  ->   26 x   26,  256
128 ActivationMish    26 x   26,  256  ->   26 x   26,  256
129 Shortcut          26 x   26,  256  ->   26 x   26,  256
130 Conv2d            26 x   26,  256  ->   26 x   26,  256
131 ActivationMish    26 x   26,  256  ->   26 x   26,  256
132 Conv2d            26 x   26,  256  ->   26 x   26,  256
133 ActivationMish    26 x   26,  256  ->   26 x   26,  256
134 Shortcut          26 x   26,  256  ->   26 x   26,  256
135 Conv2d            26 x   26,  256  ->   26 x   26,  256
136 ActivationMish    26 x   26,  256  ->   26 x   26,  256
137 Conv2d            26 x   26,  256  ->   26 x   26,  256
138 ActivationMish    26 x   26,  256  ->   26 x   26,  256
139 Shortcut          26 x   26,  256  ->   26 x   26,  256
140 Conv2d            26 x   26,  256  ->   26 x   26,  256
141 ActivationMish    26 x   26,  256  ->   26 x   26,  256
142 Route             26 x   26,  512  ->   26 x   26,  512
143 Conv2d            26 x   26,  512  ->   26 x   26,  512
144 ActivationMish    26 x   26,  512  ->   26 x   26,  512
145 Conv2d            26 x   26,  512  ->   13 x   13, 1024
146 ActivationMish    13 x   13, 1024  ->   13 x   13, 1024
147 Conv2d            13 x   13, 1024  ->   13 x   13,  512
148 ActivationMish    13 x   13,  512  ->   13 x   13,  512
149 Route             13 x   13, 1024  ->   13 x   13, 1024
150 Conv2d            13 x   13, 1024  ->   13 x   13,  512
151 ActivationMish    13 x   13,  512  ->   13 x   13,  512
152 Conv2d            13 x   13,  512  ->   13 x   13,  512
153 ActivationMish    13 x   13,  512  ->   13 x   13,  512
154 Conv2d            13 x   13,  512  ->   13 x   13,  512
155 ActivationMish    13 x   13,  512  ->   13 x   13,  512
156 Shortcut          13 x   13,  512  ->   13 x   13,  512
157 Conv2d            13 x   13,  512  ->   13 x   13,  512
158 ActivationMish    13 x   13,  512  ->   13 x   13,  512
159 Conv2d            13 x   13,  512  ->   13 x   13,  512
160 ActivationMish    13 x   13,  512  ->   13 x   13,  512
161 Shortcut          13 x   13,  512  ->   13 x   13,  512
162 Conv2d            13 x   13,  512  ->   13 x   13,  512
163 ActivationMish    13 x   13,  512  ->   13 x   13,  512
164 Conv2d            13 x   13,  512  ->   13 x   13,  512
165 ActivationMish    13 x   13,  512  ->   13 x   13,  512
166 Shortcut          13 x   13,  512  ->   13 x   13,  512
167 Conv2d            13 x   13,  512  ->   13 x   13,  512
168 ActivationMish    13 x   13,  512  ->   13 x   13,  512
169 Conv2d            13 x   13,  512  ->   13 x   13,  512
170 ActivationMish    13 x   13,  512  ->   13 x   13,  512
171 Shortcut          13 x   13,  512  ->   13 x   13,  512
172 Conv2d            13 x   13,  512  ->   13 x   13,  512
173 ActivationMish    13 x   13,  512  ->   13 x   13,  512
174 Route             13 x   13, 1024  ->   13 x   13, 1024
175 Conv2d            13 x   13, 1024  ->   13 x   13, 1024
176 ActivationMish    13 x   13, 1024  ->   13 x   13, 1024
177 Conv2d            13 x   13, 1024  ->   13 x   13,  512
178 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
179 Conv2d            13 x   13,  512  ->   13 x   13, 1024
180 ActivationLeaky   13 x   13, 1024  ->   13 x   13, 1024
181 Conv2d            13 x   13, 1024  ->   13 x   13,  512
182 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
183 Pooling           13 x   13,  512  ->   13 x   13,  512
184 Route             13 x   13,  512  ->   13 x   13,  512
185 Pooling           13 x   13,  512  ->   13 x   13,  512
186 Route             13 x   13,  512  ->   13 x   13,  512
187 Pooling           13 x   13,  512  ->   13 x   13,  512
188 Route             13 x   13, 2048  ->   13 x   13, 2048
189 Conv2d            13 x   13, 2048  ->   13 x   13,  512
190 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
191 Conv2d            13 x   13,  512  ->   13 x   13, 1024
192 ActivationLeaky   13 x   13, 1024  ->   13 x   13, 1024
193 Conv2d            13 x   13, 1024  ->   13 x   13,  512
194 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
195 Conv2d            13 x   13,  512  ->   13 x   13,  256
196 ActivationLeaky   13 x   13,  256  ->   13 x   13,  256
197 Upsample          13 x   13,  256  ->   26 x   26,  256
198 Route             26 x   26,  512  ->   26 x   26,  512
199 Conv2d            26 x   26,  512  ->   26 x   26,  256
200 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
201 Route             26 x   26,  512  ->   26 x   26,  512
202 Conv2d            26 x   26,  512  ->   26 x   26,  256
203 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
204 Conv2d            26 x   26,  256  ->   26 x   26,  512
205 ActivationLeaky   26 x   26,  512  ->   26 x   26,  512
206 Conv2d            26 x   26,  512  ->   26 x   26,  256
207 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
208 Conv2d            26 x   26,  256  ->   26 x   26,  512
209 ActivationLeaky   26 x   26,  512  ->   26 x   26,  512
210 Conv2d            26 x   26,  512  ->   26 x   26,  256
211 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
212 Conv2d            26 x   26,  256  ->   26 x   26,  128
213 ActivationLeaky   26 x   26,  128  ->   26 x   26,  128
214 Upsample          26 x   26,  128  ->   52 x   52,  128
215 Route             52 x   52,  256  ->   52 x   52,  256
216 Conv2d            52 x   52,  256  ->   52 x   52,  128
217 ActivationLeaky   52 x   52,  128  ->   52 x   52,  128
218 Route             52 x   52,  256  ->   52 x   52,  256
219 Conv2d            52 x   52,  256  ->   52 x   52,  128
220 ActivationLeaky   52 x   52,  128  ->   52 x   52,  128
221 Conv2d            52 x   52,  128  ->   52 x   52,  256
222 ActivationLeaky   52 x   52,  256  ->   52 x   52,  256
223 Conv2d            52 x   52,  256  ->   52 x   52,  128
224 ActivationLeaky   52 x   52,  128  ->   52 x   52,  128
225 Conv2d            52 x   52,  128  ->   52 x   52,  256
226 ActivationLeaky   52 x   52,  256  ->   52 x   52,  256
227 Conv2d            52 x   52,  256  ->   52 x   52,  128
228 ActivationLeaky   52 x   52,  128  ->   52 x   52,  128
229 Conv2d            52 x   52,  128  ->   52 x   52,  256
230 ActivationLeaky   52 x   52,  256  ->   52 x   52,  256
231 Conv2d            52 x   52,  256  ->   52 x   52,  255
232 Yolo              52 x   52,  255  ->   52 x   52,  255
233 Route             52 x   52,  128  ->   52 x   52,  128
234 Conv2d            52 x   52,  128  ->   26 x   26,  256
235 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
236 Route             26 x   26,  512  ->   26 x   26,  512
237 Conv2d            26 x   26,  512  ->   26 x   26,  256
238 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
239 Conv2d            26 x   26,  256  ->   26 x   26,  512
240 ActivationLeaky   26 x   26,  512  ->   26 x   26,  512
241 Conv2d            26 x   26,  512  ->   26 x   26,  256
242 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
243 Conv2d            26 x   26,  256  ->   26 x   26,  512
244 ActivationLeaky   26 x   26,  512  ->   26 x   26,  512
245 Conv2d            26 x   26,  512  ->   26 x   26,  256
246 ActivationLeaky   26 x   26,  256  ->   26 x   26,  256
247 Conv2d            26 x   26,  256  ->   26 x   26,  512
248 ActivationLeaky   26 x   26,  512  ->   26 x   26,  512
249 Conv2d            26 x   26,  512  ->   26 x   26,  255
250 Yolo              26 x   26,  255  ->   26 x   26,  255
251 Route             26 x   26,  256  ->   26 x   26,  256
252 Conv2d            26 x   26,  256  ->   13 x   13,  512
253 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
254 Route             13 x   13, 1024  ->   13 x   13, 1024
255 Conv2d            13 x   13, 1024  ->   13 x   13,  512
256 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
257 Conv2d            13 x   13,  512  ->   13 x   13, 1024
258 ActivationLeaky   13 x   13, 1024  ->   13 x   13, 1024
259 Conv2d            13 x   13, 1024  ->   13 x   13,  512
260 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
261 Conv2d            13 x   13,  512  ->   13 x   13, 1024
262 ActivationLeaky   13 x   13, 1024  ->   13 x   13, 1024
263 Conv2d            13 x   13, 1024  ->   13 x   13,  512
264 ActivationLeaky   13 x   13,  512  ->   13 x   13,  512
265 Conv2d            13 x   13,  512  ->   13 x   13, 1024
266 ActivationLeaky   13 x   13, 1024  ->   13 x   13, 1024
267 Conv2d            13 x   13, 1024  ->   13 x   13,  255
268 Yolo              13 x   13,  255  ->   13 x   13,  255
===========================================================

GPU free memory: 25.428 mb.
New NetworkRT (TensorRT v7.21)
TENSORRT LOG: CUDA initialization failure with error 2. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Errore di segmentazione (core dump creato)
`
On my laptop I have Ubuntu 18.04, kernel version 5.4.0, gcc version 8.4, GLIBC 2.27, Cuda11.1, cuDNN8.0.4, Tensort7.2.1, openCV 4.4.0

So I think I have all the requirements that cuda11.1 and tkDNN needs.

I have tried also to reinstall all of these, but I obtain anyway the error.

cmake .. and make works.

How can I fix that?

**Comment by panca1** [comment]
I've also tried now to install cuda 10.0, cuDNN 7.6, Tensorrt 6.0.1 but it give me back the same problem? 
Is it a problem of out-of-memory?

**Comment by mive93** [comment]
Hi @panca1 , 

the problem could be with CUDA version of the libraries.
Run these commands and check that cuda is always the same, as in my case (check image, always CUDA 10.2).

```
dpkg -l | grep cudnn
dpkg -l | grep nvinfer
nvcc --version
```

![image](https://user-images.githubusercontent.com/11939259/98594626-3c4d2800-22d5-11eb-9f71-37a82a65865e.png)

**Comment by panca1** [comment]
Yes, this is the problem. 

![Schermata del 2020-11-09 21-52-25](https://user-images.githubusercontent.com/55707722/98595136-e0cf6a00-22d5-11eb-9bcb-bb7f6a7a1457.png)

**Comment by panca1** [comment]
Hi @mive93 ,
I fix the problem but it give me back that.

`TENSORRT LOG: Generating copy for Upsample214_out to Route218_out
TENSORRT LOG: Eliminating concatenation Route233
TENSORRT LOG: Retargeting ActivationLeaky228_out to Route233_out
TENSORRT LOG: Eliminating concatenation Route236
TENSORRT LOG: Retargeting ActivationLeaky235_out to Route236_out
TENSORRT LOG: Retargeting ActivationLeaky211_out to Route236_out
TENSORRT LOG: Eliminating concatenation Route251
TENSORRT LOG: Retargeting ActivationLeaky246_out to Route251_out
TENSORRT LOG: Eliminating concatenation Route254
TENSORRT LOG: Retargeting ActivationLeaky253_out to Route254_out
TENSORRT LOG: Retargeting ActivationLeaky194_out to Route254_out
TENSORRT LOG: After concat removal: 273 layers
TENSORRT LOG: Graph construction and optimization completed in 0.238891 seconds.
TENSORRT LOG: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.0
TENSORRT LOG: Constructing optimization profile number 0 out of 1
*************** Autotuning format combination: Float(1,416,173056,519168) -> Float(1,416,173056,5537792) ***************
TENSORRT LOG: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
TENSORRT LOG: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
cloud not build cuda engine
/home/giacomo/Scrivania/tkDNN/src/NetworkRT.cpp:145
Aborting...
`

Is it a problem of GPU memory?

**Comment by mive93** [comment]
Yes, as the debug says, it is an out of memory problem.
