### ISSUE TITLE
how to set anchors from the code ?

### ISSUE THREAD

**Issue by HilmiiKumdakci** [ceccocats/tkDNN#145]
For Yolov3 and Yolov4 , are the anchor variables are modifiable or if they embed into the .rt file generated by tkdnn ?

**Comment by mive93** [comment]
Hi @HilmiiKumdakci 
They are embedded in the rt, once you create it.
They are loaded here: https://github.com/ceccocats/tkDNN/blob/master/src/Yolo.cpp#L23
