### ISSUE TITLE
Adaptive Anchor Box Optimization

### ISSUE THREAD

**Issue by Goru1890** [ceccocats/tkDNN#146]
I found this paper looking for a more efficient way to train YOLO, do you think this would improve detection for custom dataset?

I'm trying to train a aeroplane, drone and bird detector, most of the bounding boxes have a differents sizes, sometimes the trained files doesn't detect small object and sometimes it doesn't detect big object. 

https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123500545.pdf

**Comment by mive93** [comment]
Hi @Goru1890 

I don't know about that method. Maybe it will.
However, have you tried to compute the anchors on your dataset as explained in darknet readme?

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
