### ISSUE TITLE
Custom model, this is not yolo3 error

### ISSUE THREAD

**Issue by alexflorensa** [ceccocats/tkDNN#147]
Hello @ceccocats,

I am trying to make inference with a custom model using tkdnn demo.
I already have my trt engine (after editing tests/darknet/yolo4.cpp with new paths and compiling again) and layers from darknet (thanks to your repo). But when running demo the output is the following:
```
detection
yolo_fp32.rt
New NetworkRT (TensorRT v7.21)
Float16 support: 0
Int8 support: 1
DLAs: 0
Segmentation fault (core dumped)
```
I don't really know what to do right now. Thank you very much

**Comment by Goru1890** [comment]
How did you resolve it?

**Comment by alexflorensa** [comment]
Running it on the docker. They have an image on dockerhub or you can build
it with their Dockerfile. Maybe was a version problem: not matching their
requirements.

**Comment by AGpix** [comment]
Hi, how did you resolve this issue
