### ISSUE TITLE
Build Error: ‘blobFromImage’ is not a member of ‘cv::dnn’

### ISSUE THREAD

**Issue by Yuanye-F** [ceccocats/tkDNN#149]
[ 26%] Building CXX object CMakeFiles/tkDNN.dir/src/Int8BatchStream.cpp.o
/home/user/Downloads/tkDNN/src/Int8BatchStream.cpp: In member function ‘void BatchStream::readCVimage(std::string, std::vector<float>&, bool)’:
/home/user/Downloads/tkDNN/src/Int8BatchStream.cpp:129:33: error: ‘blobFromImage’ is not a member of ‘cv::dnn’
     m_LetterboxImage = cv::dnn::blobFromImage(m_LetterboxImage);
                                 ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/tkDNN.dir/src/Int8BatchStream.cpp.o] Error 1
make[1]: *** [CMakeFiles/tkDNN.dir/all] Error 2
make: *** [all] Error 2

while there is no problem for cmake:
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.2", minimum required is "9.0") 
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found CUDNN include: /usr/local/cuda/include
-- Found NVINFER: /usr/local/cuda/lib64/libnvinfer.so
-- Found NVINFER include: /usr/local/cuda/include
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
install dir:/usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/tkDNN/build

Please help, thanks a lot : )

**Comment by mive93** [comment]
Hi @Yuanye-F 

Do you have opencv installed?
In case, which version?
[Here](https://github.com/ceccocats/tkDNN/blob/master/scripts/install_OpenCV4.sh) you can find the script to install the required one.

**Comment by Yuanye-F** [comment]
Hi @mive93 

I have installed opencv and the version is 4.1.2.

**Comment by mive93** [comment]
I don't know, the problem is clearly related to OpenCV. 
You have to make sure that it's linked correctly. 
Is opencv installed in /usr/local/ ?

**Comment by Yuanye-F** [comment]
Thanks.  I would check if there is something wrong with OpenCV.
OpenCV is installed in /usr/local/

**Comment by mive93** [comment]
Then I don't know what to suggest. 
Are you working on a computer or embedded board?

**Comment by irvingzhang0512** [comment]
Met the same issue, try add `-lopencv_dnn` in `tkdnn_LIBS`

`set(tkdnn_LIBS kernels ${CUDA_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES} ${CUDNN_LIBRARIES} ${OpenCV_LIBS} yaml-cpp -lopencv_dnn -lopencv_videoio)`

**Comment by Yuanye-F** [comment]
> Met the same issue, try add `-lopencv_dnn` in `tkdnn_LIBS`
> 
> `set(tkdnn_LIBS kernels ${CUDA_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES} ${CUDNN_LIBRARIES} ${OpenCV_LIBS} yaml-cpp -lopencv_dnn -lopencv_videoio)`

Get it. Thanks a lot.

**Comment by Yuanye-F** [comment]
@irvingzhang0512 
Get it. Thanks a lot.
