### ISSUE TITLE
Will you support any classifier networks?

### ISSUE THREAD

**Issue by LukeAI** [ceccocats/tkDNN#15]
Do you plan to add support to any classifier networks?
Being able to run inference with the backbone of Yolov4, [CSPDarkNet-53](https://github.com/WongKinYiu/CrossStagePartialNetworks) for example, would be really nice with this repo.

**Comment by mive93** [comment]
Hi @LukeAI,

For now, we don't plan to, but tkDNN can support them without any problems. 
Classification networks are somehow a subset of object detectors, and it should be easy to port them if needed.

**Comment by mive93** [comment]
Closing for now, 
feel free to reopen.
