### ISSUE TITLE
Detect only some classes from 80 classes by default

### ISSUE THREAD

**Issue by panca1** [ceccocats/tkDNN#151]
Hi everyone!
How can I detect (yolov4) only some classes from 80? For example if I want only motorbike and car how can I do that? 
Do I have to modify yolo4.cfg and coco.names?

**Comment by mive93** [comment]
Hi @panca1 
There are two options:
- fast one: just filter out the classes that you want to show with an if (somewhere [here](https://github.com/ceccocats/tkDNN/blob/master/include/tkDNN/DetectionNN.h#L166))
- slow one: retrain the network to detect only the classes that you want (and then change everything, cfg, names, test).
