### ISSUE TITLE
How does input_bins and output_bins affect on custom data? 

### ISSUE THREAD

**Issue by Goru1890** [ceccocats/tkDNN#152]
I wrote a custom yolo4.cpp for my own dataset and trained weights, do I have to customize also the paths in input_bins and output_bins? 
For example, I don't have the layer161_out.bin in my exported weights.

I also noticed that the ap is lower in a tkDNN demo, using a jetson tx2, than in a darknet demo, using a gtx 2080.

**Comment by mive93** [comment]
Hi @Goru1890 

generally with the yolo family just check in the layer folder (with the weights) the weights that start with g, those are the output layers. For instance, with Yolov4 you will have g139, g150 and g161, that correspond to output bins layer139_out.bin, layer150_out.bin, layer161_out.bin. For other models, it depends, could be more complex, but the point is that it correspond to the number of the output layers.

What do you mean by lower ap? Which ap are you mentioning? 
MAP(0.5:0.95)? AP50? AP75? 
Darknet does not compute the AP50, we compute all of them.

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
