### ISSUE TITLE
create rt engine require more gpu memory

### ISSUE THREAD

**Issue by AllenDun** [ceccocats/tkDNN#153]
Thanks for the great work. I have a question.  It will consume much more gpu memory (about two times of normal runtime) when generate the rt engine using "./test_yolo4" .  Is there a way to avoid this?

**Comment by mive93** [comment]
Hi, try to check this https://github.com/ceccocats/tkDNN/issues/26#issuecomment-637453954
It helps to consume less memory and it allows to build the model also on the Jetson Nano.

**Comment by mive93** [comment]
Closing for now, feel free to reopen.
