### ISSUE TITLE
Set gpu id

### ISSUE THREAD

**Issue by lilong-epfl** [ceccocats/tkDNN#155]
I have multiple discrete GPUs on my machine. Is that possible to set the gpu id for inference?

**Comment by mive93** [comment]
Hi @lilong-epfl 

Right now, there is no way to do that inside tkDNN.
I usually just use the env variable CUDA_VISIBLE_DEVICES

e.g. with GPU 1
```
CUDA_VISIBLE_DEVICES=1 ./demo
```
