### ISSUE TITLE
int8 and fp16 img preprocess

### ISSUE THREAD

**Issue by ou525** [ceccocats/tkDNN#156]
Hello, thanks for sharing.
There is a question that I am quite confused. The letterbox is used for the preprocessing of int8 quantization, but the preprocessing of the demo is simple resize. Is there anything special about this?

**Comment by ceccocats** [comment]
Hi, 
The past versions of YOLO used to apply the letterbox but in the newest it switched to a resize.
I think we just forgot to update it in the quantisation.
We need to check

**Comment by ou525** [comment]
Okay, got it
