### ISSUE TITLE
Object tracking

### ISSUE THREAD

**Issue by alex-stonebridge** [ceccocats/tkDNN#163]
Hi, firstly, I want to say thanks for this repository. I have my custom Yolo NN working perfectly fine with a Xavier NX. As a next step I would like to implement object tracking. 
Could you probably share some ideas how to add this feature having your architecture as a base?

**Comment by mive93** [comment]
Hi @alex-stonebridge 
There are many option, here's what we implemented in our projects:
- Multi tracker Extended Kalman filter on a single point representing the object (as done in this project https://github.com/mive93/class-edge)
- Feature based tracking, computing the features of each BBs with classical methods (e.g. Harris, FAST etc) and track them frame by frame
- tkDNN [Center track](https://github.com/xingyizhou/CenterTrack) implementation, in this branch https://github.com/ceccocats/tkDNN/tree/cnet
