### ISSUE TITLE
Confusing about the change of fps

### ISSUE THREAD

**Issue by Elina-ye** [ceccocats/tkDNN#166]
Thank you for your work.

I'm struggling with the FPS.
I ran the demo on TX2 and the fps had achieved about 87. However, I need to report the fps during the detection and I found the fps has a low value at the beginning. Then it will be increased and reach a stable value. The whole period will cost about 1 minute.
Could anyone can tell me why the fps is low at first and has increased after that?

**Comment by mive93** [comment]
It's not a problem of tkDNN, it's very common in several application.
FPS are never constant, you should always consider the average value and the variance. 
Clearly the first iteration will be the most expensive (it has to load the model on the GPU and initialize a lot of stuff), but then it depends on what else is running on your board.

Closing for now, feel free to reopen.
