### ISSUE TITLE
threshold?

### ISSUE THREAD

**Issue by harsco-jfernandez** [ceccocats/tkDNN#17]
Does the concept of threshold like in darknet exists?

**Comment by mive93** [comment]
Hi @harsco-jfernandez,

yes there is. Unfortunately it's not a parameter (but it should be, my bad). You have to change it manually in include/tkDNN/DetectionNN.h, the parameter confThreshold.

**Comment by harsco-jfernandez** [comment]
thank you @mive93 
Yes, I found it 2 secs after I posted :smirk: and it works well.
