### ISSUE TITLE
difference of yolov4x-mish.cfg between yours and Alexey

### ISSUE THREAD

**Issue by erikguo** [ceccocats/tkDNN#179]
hi, thank you for your great job!

I found there's one difference of yolov4x-mish.cfg between yours and Alexey. 

The activation func just before yolo layer is linear in your yolov4x-mish.cfg while the func is logistic in Alexey version. Why do you change the activation func? 

And if I use the version from Alexey, it will report 'don't support'.

@ceccocats

**Comment by mive93** [comment]
Hi @erikguo 
We used the cfg file that Alexey gave us when he firstly released yolov4x-mish. So, it's still the original one, while I think he has changed his. 
I will check on that.

**Comment by AlexeyAB** [comment]
Previously logistic activation (sigmoid) was used inside [yolo] layer. 
Currently we use logistic activation (sigmoid) in the previous conv-layer.

**Comment by mive93** [comment]
Fixed with the last commit https://github.com/ceccocats/tkDNN/commit/adac8576b0faf515ad3f459b1f50fd16cef6d64d
