### ISSUE TITLE
yolov3 network with different backbone

### ISSUE THREAD

**Issue by AllenDun** [ceccocats/tkDNN#18]
appreciate your nice work. How to use tkDNN if I have a yolov3 network with customed backbone? for model exportation, is there any difference? for test inference, I just need to modify the file "yolov3.h" or any other codes?
Thanks!

**Comment by ceccocats** [comment]
Hi,
Is it made with darknet?
If so, you need to export the weights as described in the readme. Then you have to change yolov3.h according to your backbone cfg.

**Comment by AllenDun** [comment]
yes, trained with darknet. Thanks, I will try it and use tfDNN on the jetson nano.

**Comment by mive93** [comment]
Closing for now, 
feel free to reopen.
