### ISSUE TITLE
Yolov4-scaled

### ISSUE THREAD

**Issue by AleBasso80** [ceccocats/tkDNN#180]
Hi,
I tried to export the AlexeyAB yolov4-scaled weights by means of your forked darknet version. I got an assert error at layer 273, I guess that this network is not supported yet. Do you have any plan to do it?

Thanks
Alessandro

**Comment by erikguo** [comment]
There's a pull request to support logistic activation. You can tried.    But I found the layer activation just before [yolo] layer is using linear not logistic.

**Comment by mive93** [comment]
Hi @AleBasso80 
I did not know about this new addition.
I will look on that in the next days.

**Comment by AleBasso80** [comment]
Hi @mive93,
thanks. Its developers claim that this is new state-of-the-art detector.

**Comment by AlexeyAB** [comment]
@mive93 
Previously logistic activation (sigmoid) was used inside [yolo] layer.
Currently we use logistic activation (sigmoid) after the previous conv-layer.

**Comment by LukeAI** [comment]
@mive93  scaled-yolo is SOTA - would be great to see support for it here

AlexeyAB's medium: https://alexeyab84.medium.com/scaled-yolo-v4-is-the-best-neural-network-for-object-detection-on-ms-coco-dataset-39dfa22fa982

Paper: https://arxiv.org/abs/2011.08036

github: https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-large

**Comment by mive93** [comment]
Hi all @AlexeyAB @LukeAI @AleBasso80 @erikguo.
Scaled Yolo 4 is now supported 

https://github.com/ceccocats/tkDNN/commit/adac8576b0faf515ad3f459b1f50fd16cef6d64d

**Comment by AleBasso80** [comment]
Hi @mive93, wonderful... Thanks a lot!!
