### ISSUE TITLE
get "Wrong" error when I convert to yolo4_fp16.rt

### ISSUE THREAD

**Issue by younger-diao** [ceccocats/tkDNN#188]
There is not any wrong when I convert to yolo4_fp32.rt,but get "Wrong" error when I convert to yolo4_fp16.rt.
![wrong](https://user-images.githubusercontent.com/24713981/105121917-3020ea80-5b10-11eb-9e41-5f2eef4a3f9c.jpg)

**Comment by younger-diao** [comment]
Although there are some wrongs during converting to yolo4_fp16.rt, it is normal by testing the yolo4_fp16.rt.

**Comment by mive93** [comment]
It is totally normal, you are quantizing, so you have small errors. 
However, the results are very fine (in all my experience).

**Comment by younger-diao** [comment]
OK. I got it. Thanks a lot!
