### ISSUE TITLE
Support for RTX 3080

### ISSUE THREAD

**Issue by shubham-shahh** [ceccocats/tkDNN#190]
As cuda 10 does not support Ampere architecture, i cannot run cuda 10 on RTX 3080, so my question is, does tkdnn has support for cuda 11?

**Comment by syjeon121** [comment]
i worked fine on cuda 11.1

**Comment by mive93** [comment]
Hi @shubham-shahh 
Yes, CUDA 11 is supported. The only problem that I lately experiences is with CUDNN 8.1.
We will check it in the next days.

Thanks @syjeon121 :)
