### ISSUE TITLE
Is there a way similar to trtexec --loadEngine for just testing the speed of the model? 

### ISSUE THREAD

**Issue by ysyyork** [ceccocats/tkDNN#202]
For pure tensorrt engines, I can easily test the throughput by `trtexec --loadEngine` and it will randomly generate the inputs with required shape and measure the inference time. Is there a similar function here? Thanks.

**Comment by rickymedrano** [comment]
+1, would also like to be able to test theoretical inference. Tried using the .rt file with trtexec but it doesn't work.

**Comment by mive93** [comment]
Hi @ysyyork  and @rickymedrano , you can use the test_rtinference, e.g., with yolov4 and 1 batch:
```
    ./test_rtinference yolo4_fp32.rt 1 
```

**Comment by ysyyork** [comment]
> Hi @ysyyork and @rickymedrano , you can use the test_rtinference, e.g., with yolov4 and 1 batch:
> 
> ```
>     ./test_rtinference yolo4_fp32.rt 1 
> ```

Thanks @mive93 ! this is very helpful!
