### ISSUE TITLE
when to set pad to 0?

### ISSUE THREAD

**Issue by harsco-jfernandez** [ceccocats/tkDNN#21]
Hi,

I've noticed that sometimes padding is set to 0 while the model(darknet cfg file) has it set to 1. When should padding be set to 0 in a Conv2d obj?

tk::dnn::Conv2d c17( &net, 33, 1, 1, 1, 1, 0, 0, c17_bin, false );

Also, there is no swich activation, right?

Thank you!

**Comment by ceccocats** [comment]
Hi,
According to darknet code when you see "pad" in the cfg it means that the padding is half the kernel size, so in this case 1/2 = 0
https://github.com/AlexeyAB/darknet/blob/16a9b02e6400933e012409ea9e738f770b4a874a/src/parser.c#L160
