### ISSUE TITLE
Keep getting "Not supported field" error

### ISSUE THREAD

**Issue by Duarte-Nunes** [ceccocats/tkDNN#215]
High, im running the repository on the Jetson Nano 2Gb, and i keep getting this error (sorry for the bad quality, had to take the picture with my phone), i tried rebooting but it didnt change.

I'm just running the ./test_yolov4 that comes with the repository.

![imagem](https://user-images.githubusercontent.com/72693491/113771619-8539c900-971b-11eb-826e-09e1cb786671.png)

**Comment by mive93** [comment]
Hi @Duarte-Nunes, check this: https://github.com/ceccocats/tkDNN/issues/26

**Comment by Duarte-Nunes** [comment]
Some further elaboration, i do believe that the problem is still low memory however i am running the jetson only on terminal the max memory usage is 500mb which leaves around 6 gb of free memory (including swap) but when i run the test it says "GPU free memory: 100mb" or 70 mb ou around those values

**Comment by Duarte-Nunes** [comment]
@mive93 Nevermind it appears through some research on Nvidia forums that Cuda device memory cannot be swaped and therefore even with the trick posted on the Issue you linked my Jetson nano which is a 2Gb model cannot run the code.
