### ISSUE TITLE
input size for yolo4_berkeley

### ISSUE THREAD

**Issue by feritte** [ceccocats/tkDNN#217]
Hello,

Firts of all thanks a lot for the great repository. I am able to build the project and run your demo code but I have a question about yolo4_berkeley input size. According to the table "Existing tests and supported networks"  the input size is 540x320 for yolo4_berkeley but when i run the demo, I see the input size is 544x320 (the same as yolov3). Is it normal or just a typo on the table ? 

Thanks in advance.

Regards

Ferit

**Comment by mive93** [comment]
Hi @feritte,
yep, it's just a typo of the table. Thanks for the notice :)
