### ISSUE TITLE
 How should I use the USB camera to detect in real time with this repo???

### ISSUE THREAD

**Issue by qrzeffort** [ceccocats/tkDNN#219]
According to the issue#96 I have tried to use dev/video0 to substitute yolo_test.mp4, but it did not run successfully.
And how to modify demo.cpp to use the USB camera like the original YoloV4 code? 
Like this: **darknet.exe detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -c 0** 
-->**./demo yolo4_fp32.rt -c 0 y** 

ps:"'path-to-video' is the path to a video file or a **camera input**",Could you give an example of the "camera input"? It is not explained in the readme.md.Thank you~

**Comment by SokPhanith** [comment]
if you want detect video : ./demo yolo4_fp32.rt test.mp4 y
if you want detect camera (jetson board) : ./demo yolo4_fp32.rt /dev/video0 y
     - but something you need change port camera like /dev/video1 , /dev/video2.
     - check camera on jetson board : ls /dev/video* 
if you want detect camera (windows) ./demo yolo4_fp32.rt 0 y port camera (0,1,2)
