### ISSUE TITLE
can a PAN3 network work in tkDNN?

### ISSUE THREAD

**Issue by harsco-jfernandez** [ceccocats/tkDNN#22]
Hi,

PAN3 has a few properties that I'm uncertain if these are only training augmentation or completely new layers that can affect inferencing. 

Can a PAN3 network work in tkDNN? Are all the elements of it implemented?

If so, how would I set this up in Conv2d and Pooling? In particular stride_x and stride_y. 

[maxpool]
size=8
stride=4
stride_x=4
stride_y=8

[convolutional]
batch_normalize=1
filters=64
size=1
stride=2
stride_x=2
stride_y=1
pad=1
activation=mish

Thank you!

**Comment by mive93** [comment]
Hi @harsco-jfernandez ,
Yes, everything is supported, but we do not have the parser. So you have to write the layers yourself.

**Comment by ceccocats** [comment]
The parser is now avaible
https://github.com/ceccocats/tkDNN#darknet-parser
