### ISSUE TITLE
darknet parser not supported field

### ISSUE THREAD

**Issue by feritte** [ceccocats/tkDNN#222]
Hi, 

Thanks a lot for your great project. 

I exported yolov4-csp model weights trained on a custom dataset by using the given fork of darknet as it is explained on readme. Then using test_yolo4-csp (given the right right names and layers/debug file) I converted it to a rt model. Although it creates a rt model file, i see many "not supported field" lines during the conversion

![tkDNN_converting_to_rt_model](https://user-images.githubusercontent.com/7426964/115243695-7c85c180-a123-11eb-89c7-aea042c5d0a0.png)

![tkDnn_converting_2_rt_model_003](https://user-images.githubusercontent.com/7426964/115243886-ad65f680-a123-11eb-842e-983939898468.png)

At the end I have a rt file which I can load it and use it with demo executable but I would like to know if these are just normal warnings or the conversion is not done correctly.

Thanks again.

Regards

Ferit

**Comment by mive93** [comment]
Hi @feritte,

yes, that is totally normal. It's just the parser that do not support those values (that are used for training on darknet, and not useful for inference). If the demo works fine, everything is ok :)
