### ISSUE TITLE
tkDNN vs TensorRT

### ISSUE THREAD

**Issue by elias-work** [ceccocats/tkDNN#241]
Hopefully this isn't a silly question and it is ok to ask here, I am having a hard time finding the answer. I am looking into accelerating my yolov4 inference on desktop hardware, and currently am using TensorRT itself. I am wondering what tkDNN effectively does in addition: is it mainly for jetson boards, performance improvements over TensorRT, more supported models, etc.?

**Comment by mive93** [comment]
Hi @elias-work, indeed it is what you guessed. 
tkDNN is an easy to use and to integrate wrapper to tensorRT to optimize custom models of NN for C++ applications.
