### ISSUE TITLE
low fps in AGX XAVIER

### ISSUE THREAD

**Issue by AlanNewImage** [ceccocats/tkDNN#248]
Hi:

I test yolo4tiny in AGX use newest repo ,only achieved about 120fps.
launched jetson_clocks
test by test_rtinference
test in two diffrent AGX Xavier and have the same result

Output Buffers: 2
Output Buffers: 2
Output Buffers: 2
Output Buffers: 2
avg: 8.43752

**Comment by AlanNewImage** [comment]
Output Buffers: 3
Output Buffers: 3
Output Buffers: 3
Output Buffers: 3
avg: 37.9915
this is yolo4_berkely_fp16,only 26fps
download weights from this repo, and convert model to .rt by test_yolo4_berkeley

**Comment by sapienzadavide** [comment]
Hi @AlanNewImage 
What is the commit/branch you are working on? 
Thank you

**Comment by AlanNewImage** [comment]
branch master

I get 244fps for yolo4tiny_fp16 based the newest commit, but only 29fps for yolo4_berkeley_fp16.

**Comment by sapienzadavide** [comment]
What is the NV power mode? (try MAXN)

**Comment by AlanNewImage** [comment]
Thanks for your reply;
CUDA: 10.2
TensorRT: 7.1.3
cudnn: 8.0.0.180

**Comment by AlanNewImage** [comment]
Thank you very much!
I get 335 fps after set nvpmodel to 0 .
WOW,it's amazing.
Thanks again.
