### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ariharasudhanm** [ceccocats/tkDNN#251]
Error limit reached.
100 errors detected in the compilation of "/home/dir/tkDNN/src/kernels/normalize.cu".
Compilation terminated.
CMake Error at kernels_generated_normalize.cu.o.cmake:280 (message):
  Error generating file
  /home/dir/tkDNN/build/CMakeFiles/kernels.dir/src/kernels/./kernels_generated_normalize.cu.o

make[2]: *** [CMakeFiles/kernels.dir/build.make:3732: CMakeFiles/kernels.dir/src/kernels/kernels_generated_normalize.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:90

**Comment by mive93** [comment]
Can you give further details? How did you get this error? On which board/OS?

**Comment by ariharasudhanm** [comment]
There were some problems with cuda and CudNN, Tensorrt versions so now it's
perfectly fine after installing the correct matching versions of all three.

**Comment by mive93** [comment]
Ok cool, then I'm closing the issue.

**Comment by ariharasudhanm** [comment]
Thank you!

**Comment by sleepingsaint** [comment]
I am getting the same error, can anyone help me with this issue.
![Screenshot from 2021-10-11 12-21-05](https://user-images.githubusercontent.com/35530053/136745128-5fefe739-d3ae-46ed-8335-a4d91b3f7b1a.png)


![Screenshot from 2021-10-11 12-22-40](https://user-images.githubusercontent.com/35530053/136745276-3921feae-c17e-4445-81da-8415fdb4f142.png)

I added the screenshots of the tensorrt, cudnn and, cuda version

Any help is very much appreciated. Thanks in advance :)

**Comment by perseusdg** [comment]
tensorrt-8 isn't supported at the moment,it is a work in progress ,the latest supported tensorrt version by tkDNN is 7.x

**Comment by perseusdg** [comment]
my guess is that you aren't linking opencv libraries properly
