### ISSUE TITLE
int8.rt unable to generate

### ISSUE THREAD

**Issue by B1ackg0d** [ceccocats/tkDNN#253]
I want to get yolo4tiny_int8.rt or other version of yolo4's int8.rt. I use test_all_tests.sh, but an error is reported.
Can I ask a favour?Thanks in advance.
```
failed to open ../demo/COCO_val2017/all_images.txt
..\src\Int8BatchStream.cpp:69
Aborting...
unable to read serialRT file
..\tests\test_rtinference\rtinference.cpp:9
Aborting...
```

**Comment by perseusdg** [comment]
Did you download COCO_val2017/BDD dataset using either the download_validation.sh(for linux) or download_validation,py(for windows) before running test_all_tests.sh ,also I would recommend against doing this as it will take a considerable amount of time to complete  (as it has to download all weights and generate the RT file for each and everyone of them) ,it might be better to follow the INT8 method mentioned in the docs

**Comment by B1ackg0d** [comment]
I get it.Thx!

**Comment by B1ackg0d** [comment]
download_validation.py is so slow, is there any better way?
