### ISSUE TITLE
'darknet.exe export ' doesn't work in Windows version

### ISSUE THREAD

**Issue by B1ackg0d** [ceccocats/tkDNN#254]
I want to use darknet to export yolo4.weights on windows, and then use tkdnn-windows to generate rt files.
It seems that darknet does not have this feature（export weights） on Windows.Do i have a better way to export weights on Windows？
Could you help me?Thx!

**Comment by perseusdg** [comment]
you could use a linux vm or wsl to export the weights

**Comment by B1ackg0d** [comment]
![image](https://user-images.githubusercontent.com/50610732/129478782-27d7e676-3d3e-4cd1-99f4-0c26ba0dc85e.png)
Hi, perseusdg.How to fix Error MSB372? I changed the `compute_61,sm_61`,bur it doesn't work.

![image](https://user-images.githubusercontent.com/50610732/129478856-ce05dd84-d520-4518-8cde-82bf4c88a929.png)
![image](https://user-images.githubusercontent.com/50610732/129478915-7ab440ed-dce2-4d54-ba74-7540806a30d3.png)
