### ISSUE TITLE
After generating .rt, there is no check boxes when using demo.exe to test

### ISSUE THREAD

**Issue by B1ackg0d** [ceccocats/tkDNN#256]
After the .rt is generated, the display is as follows：
![image](https://user-images.githubusercontent.com/50610732/130055428-f1415930-dc52-4a32-8822-d818e86873be.png)

**Comment by mive93** [comment]
It seems like the debug file are missing. 
Does the demo work? 
Which steps did you follow to reach that result?

**Comment by B1ackg0d** [comment]
Hi,mive93!I thought the debug file was not necessary, so I didn’t care about it.
I first used darknet to export the weights. Then I changed the names and cfg files under tkdnn/test/darknet. Then use test_yolo4.exe to generate the rt file, it is as shown in the figure above. Then I run demo.exe to test rt file, and I find that there is no check boxes.

**Comment by mive93** [comment]
You should export the debug and check if the conversion works fine.

**Comment by B1ackg0d** [comment]
This is what it says in the document，‘if you need debug export of every layer ouput you MUST compile in CPU mode’,I’m not sure how to compile with cpu, so I didn’t use.

**Comment by mive93** [comment]
It's quite easy, just leave ```GPU=0``` in darknet makefile

**Comment by B1ackg0d** [comment]
Thank you very much! I will try it. After modifying it, recompiling, and then using export, will there be a debug file?

**Comment by mive93** [comment]
A debug folder. Just create the debug and layers folder in advance.

**Comment by B1ackg0d** [comment]
Thank you for your reply! I have another question. Do the parameters in the training cfg, the exported cfg and the cfg used by tkdnn all need to be consistent?Especially the size of batchsize.

**Comment by mive93** [comment]
Yes, they need to be consistent, but the batch size of that config (only used for training) is not used in tkDNN.

**Comment by B1ackg0d** [comment]
> It's quite easy, just leave `GPU=0` in darknet makefile
If I use VS2019 to compile darknet, can I just use this sln directly?
![image](https://user-images.githubusercontent.com/50610732/130220409-4cfd4e95-4078-42a4-901a-cfca2fbf1bbd.png)
