### ISSUE TITLE
3080Ti could not build cuda engine

### ISSUE THREAD

**Issue by lswgh** [ceccocats/tkDNN#264]
Hi,I build the demo with cuda10.2, cudnn7.6.5  and TensorRT-7.0.0.11 in nvidia 3080Ti，when i  convert the yolov3 weights to rt , the error appear as follow:
![budl](https://user-images.githubusercontent.com/58289826/132812422-9c3996fc-11fe-45f7-9207-ab7bbf8c480f.jpg)
so i convert the weights  in my 1080Ti ，it work well  ,but when i copy the rt weight to 3080Ti, and run ./demo  yolo3_fp16.rt   ../demo/yolo_test.mp4  y  
![run](https://user-images.githubusercontent.com/58289826/132813530-023a0dcf-5081-41c8-a2b5-400a3d7f1133.jpg)

**Comment by perseusdg** [comment]
I doubt a 3080ti supports cuda 10.2,you might want to try cuda 11.1 +

**Comment by lswgh** [comment]
> I doubt a 3080ti supports cuda 10.2,you might want to try cuda 11.1 +
> https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

thanks for you concern , 
i try to build the demo with tensort7.2 cuda11.2 cudnn8.1 and  tensort8.0 cuda11.2  cudnn8.1 ,but failed , 

![tensort8-cuda11](https://user-images.githubusercontent.com/58289826/132821537-565889d3-f3bd-465a-83fa-61e2c0c555f2.jpg)

I doubt that TKDNN is  not support cuda11.1 + .

**Comment by perseusdg** [comment]
tkdnn doesnt support tensorrt 8+,i have used tkDNN tensorrt7.2+cuda11.1+ cudnn8.1.1 (if you want to use tensorrt 7.2 with cuda 11.2 you still need cuda 11.1 because nvrtc from cuda 11.1 is still a reuqirement of tensorrt 7.2 https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html#rel_7-2-3

**Comment by lswgh** [comment]
> .2+
Thanks , when i build with tensorrt7.2 cuda11.1 cudnn8.1 , it works , but compare to the 1080Ti(900M for FP32) , the memory run on 3080Ti used more (about 2.9G for FP32 and  2.5G for FP16),
