### ISSUE TITLE
Parser?

### ISSUE THREAD

**Issue by harsco-jfernandez** [ceccocats/tkDNN#27]
Hi @ceccocats and thanks for the parser. It is very useful. 

How can I deal with the maxpool layer below? It is not compatible. 

Any advice is appreciated. 

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=mish

[route]
layers=-1, -3, -6, -9, -12, -15, -18, -21, -24, -27

**[maxpool]
maxpool_depth=1
out_channels=64
stride=1
size=1**

########### [yolo-1]

[upsample]
stride=4

[route]
layers = -1,24

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=mish

Also, I had to add the following to deal with carriage return chars.
           found = line.find("\r");
            if ( found != std::string::npos ) {
                line = line.substr(0, found);
            }

**Comment by ceccocats** [comment]
Not al layers and parameters are supported right now, see DarknetParser.h
