### ISSUE TITLE
yolo object detection on images

### ISSUE THREAD

**Issue by seounghyeon** [ceccocats/tkDNN#277]
Hello,

how can I process an image instead of a video stream?

**Comment by mive93** [comment]
Hi @seounghyeon , 

if it is just an image, you can pass the path as the input instead of a path of a video. 
But in that case you want to see the results, you have to change the demo here (https://github.com/ceccocats/tkDNN/blob/master/demo/demo/demo.cpp#L138) and put 

```
cv::waitKey(0);
```

**Comment by seounghyeon** [comment]
Thank you!
