### ISSUE TITLE
Yolo3Detection segfault on cv::resize - Jetpack 5.0

### ISSUE THREAD

**Issue by ckurtz22** [ceccocats/tkDNN#300]
Running the Yolo3Detection class in Jetpack 5.0. When I call Yolo3Detection::update, I get a segfault, as shown in gdb below:
![image](https://user-images.githubusercontent.com/14020943/216831717-195445f9-1643-470b-bc48-c468cf439886.png)

**Comment by ckurtz22** [comment]
Seems the issue is that jetpack has installed 2 versions of OpenCV, 4.5.4 and 4.2.0. I'm using tkDNN inside a larger CMake project, and that CMake project is targeting OpenCV 4.2.0 (cv_bridge from ROS Noetic), and tkDNN is targeting the OpenCV 4.5.4 version. Struggling to find a way to make these packages play nice

**Comment by ckurtz22** [comment]
Was able to resolve it by manually building and installing opencv and then running the uninstall make target to remove the 4.5.4 files, so only 4.2.0 was left in the system. Now tkDNN targets the 4.2.0 opencv

**Comment by ChanJoon** [comment]
your thread was helpful for me. I resolve this issue by manually building cv_bridge with my OpenCV version. (In my case 4.8.0 and 4.2.0(noetic))
