### ISSUE TITLE
Import ONNX and test model

### ISSUE THREAD

**Issue by nViso** [ceccocats/tkDNN#31]
Hi,

We have an object detector based on ShuffleNetv2 with an ONNX exported model we would like to test in tkDNN. What is the best way to get started with an ONNX based model?

Thanks,
Tim

**Comment by ceccocats** [comment]
Onnx is currently not supported by tkdnn but is supported by tensorrt, use the official converter

**Comment by ceccocats** [comment]
Anyway it can be useful to integrate the onnx and tensorflow converter in tkdnn.
And directly manage the needed plugins.

**Comment by mive93** [comment]
Closing for now, 
feel free to reopen.

**Comment by mive93** [comment]
Hi @juancornet 
no, there a no new advancement for now.
