### ISSUE TITLE
Typo in install_OpenCV4.sh

### ISSUE THREAD

**Issue by cylee81** [ceccocats/tkDNN#32]
Hi,

Thank you for your work! 
I think in https://github.com/ceccocats/tkDNN/blob/3ea23815a4d84c04f2eae8975a2744fa9169d759/scripts/install_OpenCV4.sh#L65

In order to successfully run the script, the quotation marks after cd should be removed.

Thank you!

**Comment by mive93** [comment]
Hi @cylee81,
have you been able to run it successfully? 
I did on my laptop as it is now, but maybe it's better removing those :) Thanks

**Comment by cylee81** [comment]
Thank you 😁
