### ISSUE TITLE
Memory leak in test.h

### ISSUE THREAD

**Issue by JoeCool90** [ceccocats/tkDNN#36]
In test.h data is being set via the call to readBinaryFile with a call to cudamalloc, but I'm not seeing a corresponding cudafree.

Sorry if I misread the code.

**Comment by ceccocats** [comment]
Im aware that there are a lot of memory leaks.
For the tests is not a problem, they are meant to be run alone and once finished OS should do the work.
When using readBinaryFile you should delete the memory once is not used anymore.
I still need to recheck all the memory alloc to find some memory leaks especially in the layers.
