### ISSUE TITLE
CUDA_cublas_device_LIBRARY (ADVANCED)

### ISSUE THREAD

**Issue by deep-practice** [ceccocats/tkDNN#39]
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found CUDNN include: /usr/local/cuda/include
-- Found NVINFER: /usr/local/TensorRT-7.0.0.11/lib
-- Found NVINFER include: /usr/local/TensorRT-7.0.0.11/include
install dir:/usr/local
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "tkDNN" in directory /home/work/deep_learning/tkDNN

**Comment by ceccocats** [comment]
This is a known issue on Ubuntu 18 apt cmake.
You need to install at least cmake 3.15

**Comment by deep-practice** [comment]
Thx.It works.

**Comment by kochsebastian** [comment]
I'm trying to run it on a Jetson Xavier. For that only Cmake 3.10.2 is availible. Any solutions for that?

**Comment by mive93** [comment]
Hi @kochsebastian 
Just download a later version (https://cmake.org/download/), unzip and compile cmake. 
You can compile cmake with cmake itself by doing, in the extracted folder:

```
cmake .
make      
make install
```

**Comment by kochsebastian** [comment]
The problem is the Jetson Xavier has an arm architecture and I only see x86_64 versions on the Cmake download page

**Comment by mive93** [comment]
That's why you have to compile it. 
Download this: https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2.tar.gz
Unzip it, then move inside the unzipped folder and finally
```
mkdir build
cd build
cmake ..
make -j4
make install
```

**Comment by rickymedrano** [comment]
> That's why you have to compile it.
> Download this: https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2.tar.gz
> Unzip it, then move inside the unzipped folder and finally
> 
> ```
> mkdir build
> cd build
> cmake ..
> make -j4
> make install
> ```

For anybody having issues with cmake still on Jetson,I had to run `sudo make install` for last step. Also make sure to uninstall the old cmake first with:
`sudo apt remove --purge --auto-remove cmake`
