### ISSUE TITLE
why INT8 need TKDNN_CALIB_IMG_PATH and TKDNN_CALIB_LABEL_PATH ?

### ISSUE THREAD

**Issue by wu-ruijie** [ceccocats/tkDNN#43]
I have not idea why INT8 need image and label, thanks !

**Comment by mive93** [comment]
They are needed for the calibration. 
From tensorRT documentation: 
> When generating networks in 8-bit integer precision, it uses a process called calibration to determine the dynamic range of intermediate activations, and hence the appropriate scaling factors for quantization.

Once the calibration table is computed, the images are not used anymore.

**Comment by wu-ruijie** [comment]
thanks very much，the INT8 is ok now !

**Comment by wu-ruijie** [comment]
thanks very much，the INT8 is ok now !
