### ISSUE TITLE
Error when caculate map 

### ISSUE THREAD

**Issue by buiduchanh** [ceccocats/tkDNN#45]
@ceccocats 
Hello, I have a small problem. I train yolov4 with my dataset (13 class), I prepare test data follow this step : 
- 2 foloder ./images and ./labels. Each .txt in labels has seperate line which follow format : 
`label x_center_box/img_width y_center_box/img_height width_box/img_width height_box/img_height `
- New config file like below

<img width="646" alt="Screen Shot 2020-06-18 at 11 51 44 AM" src="https://user-images.githubusercontent.com/30837603/84979631-1b373f80-b15a-11ea-960f-aa7d82613e93.png">

but when I run ./map_demo I have a problem 

<img width="647" alt="Screen Shot 2020-06-18 at 11 48 30 AM" src="https://user-images.githubusercontent.com/30837603/84979669-33a75a00-b15a-11ea-8c92-0a399caed423.png">

Can you help me ? Thanks

**Comment by mive93** [comment]
Hi @buiduchanh,

did you solve it?

**Comment by buiduchanh** [comment]
@mive93 Sorry for late reply, I reslove this problem. This error comes from function for generate json result. I just turn off this flag and finish it
