### ISSUE TITLE
export from mmdet,detectron 2

### ISSUE THREAD

**Issue by cszer** [ceccocats/tkDNN#5]
Hello ,thanks for this awesome project. I have already red all code base  . I have some questions about converting models. On what code files should i rely while writing my_net.cpp ? What about using plugins from tensorrt library like RoIAlign etc? Please , if it is possible can you create file like python model code line -> cpp model corresponding code line , i think it will be good practical gide for converting and contributing

**Comment by ceccocats** [comment]
Hi,
I haven't have written a guide but you can find some examples with python models: https://github.com/ceccocats/tkDNN/tree/master/tests/mnist
https://github.com/ceccocats/tkDNN/tree/master/tests/simple
