### ISSUE TITLE
Why does yolov3 run slower on Tesla T4 than on RTX2080ti？

### ISSUE THREAD

**Issue by rotorliu** [ceccocats/tkDNN#50]
GeForce RTX 2080 Ti：FP16 (half) performance 26.90 TFLOPS (2:1)
Tesla T4：FP16 (half) performance 65.13 TFLOPS (8:1)

**Images Per Second**
 BatchSize | T4 | RTX2080ti
-- | -- | --
1 | 145.507 | 197.528
2 | 241.571 | 286.453
4 | 260.832 | 430.495
8 | 265.315 | 520.995
16 | 283.619 | 488.933
32 | 256.451 | 550.153
64 | 245.872 | 554.456
128 | 243.505 | 547.426
256 | 228.099 | ——

PS：Testing with tkDNN

**Comment by mrhosseini** [comment]
Actually RTX2080ti is faster than Tesla T4. See the below links:

https://www.servethehome.com/nvidia-tesla-t4-ai-inferencing-gpu-review/4/

https://versus.com/en/nvidia-geforce-rtx-2080-ti-founders-edition-vs-nvidia-tesla-t4

**Comment by rotorliu** [comment]
@mrhosseini Thank you
 Why is it that T4 FLOPs is higher but slower？

**Comment by mrhosseini** [comment]
> Why is it that T4 FLOPs is higher but slower？
On FP32 RTX2080ti is faster. On FP16 T4 has a higher FLOPS and should be faster. If not may be possible bug in tkDNN or TensorRT. May be not you are not using the latest version TensorRT.

**Comment by rotorliu** [comment]
> > Why is it that T4 FLOPs is higher but slower？
> 
> On FP32 RTX2080ti is faster. On FP16 T4 has a higher FLOPS and should be faster. If not may be possible bug in tkDNN or TensorRT. May be not you are not using the latest version TensorRT.

The table above is the result of FP16 mode. The TensorRT version is v7. So I am confused.
The code is used：
https://github.com/ceccocats/tkDNN/blob/master/tests/test_rtinference/rtinference.cpp

**Comment by rotorliu** [comment]
![image](https://user-images.githubusercontent.com/494495/85226164-a9d0e880-b408-11ea-8fdf-927c59398249.png)
This test also shows that T4 is relatively slow.

**Comment by ceccocats** [comment]
![Screenshot_20200621_192842](https://user-images.githubusercontent.com/11562617/85231203-818bbe80-b3f5-11ea-96fd-e25a8b358d7a.jpg)

![Screenshot_20200621_192724](https://user-images.githubusercontent.com/11562617/85231212-8b152680-b3f5-11ea-8fbb-b5845e085562.jpg)

Source:
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/technologies/turing-architecture/NVIDIA-Turing-Architecture-Whitepaper.pdf&ved=2ahUKEwjwsLzNtZPqAhXC3KQKHUJfCLUQFjAGegQIARAB&usg=AOvVaw3CuG9m9TLCpXjybLqkvyJR&cshid=1592760127145

**Comment by rotorliu** [comment]
Thanks
