### ISSUE TITLE
How to select which GPU using when running tkdnn

### ISSUE THREAD

**Issue by vitotsai** [ceccocats/tkDNN#51]
Hi,
I have multiple GPUs on my machine, and i can run yolov4 object detection.
How to config using different GPU device when running tkdnn?
Please guide me, thank you.

**Comment by ceccocats** [comment]
Hi,
The isn't any API for this in tkdnn.
You can launch your exe with the env variable CUDA_VISIBLE_DEVICES

**Comment by vitotsai** [comment]
HI,
Thanks for your effort and reply.
