### ISSUE TITLE
Error with new yolov4 config 

### ISSUE THREAD

**Issue by buiduchanh** [ceccocats/tkDNN#58]
@ceccocats  @mive93 

Hello. I have a small question. I check update of @alexeyAB for new yolov4 with mish activation, this is the new config 
https://drive.google.com/file/d/1V726wzWW1iBDcJ7uP8c0n_Y4M98lIg-C/view

I train the model with this config but when It can not export to `layers` and `debug`. The error I mentioned below 
<img width="866" alt="Screen Shot 2020-06-25 at 2 55 20 PM" src="https://user-images.githubusercontent.com/30837603/85679832-f57adf00-b6f3-11ea-92ab-0c4aa3b6b1f7.png">

This is the layer 137, Alexab add new layer "scale Layer" - Sam layer and I think this is the main reason

<img width="714" alt="Screen Shot 2020-06-25 at 2 55 37 PM" src="https://user-images.githubusercontent.com/30837603/85679957-13e0da80-b6f4-11ea-9080-f386bcfa19f6.png">

Can you share your solution for fix it ? Thanks

**Comment by ceccocats** [comment]
Hi,
Where is? I can't find it in Alexey repo.
If it has a better map we will implement it for sure.

**Comment by buiduchanh** [comment]
@ceccocats  
This is in yolov4 model zoo : YOLOv4-SAM-Mish
https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo
It add Sam layer so may be cause bug

**Comment by ceccocats** [comment]
Yes is a new layer.
Looking at the code it seems a shortcut with multiplication instead of sum and an activation.
We already have the shortcut with mul in the branch segmentation. Maybe next week we will merge in master.

**Comment by Goru1890** [comment]
How much does YOLOv4-SAM-Mish improve detection over YOLOv4?

**Comment by mive93** [comment]
Hi @Goru1890, that's more a question for the developers od yolov4.
However, [here](https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo#yolov4-model-zoo) is the answer at your question:

![image](https://user-images.githubusercontent.com/11939259/99275833-410d6100-282c-11eb-9fb7-3d723b81eed4.png)
