### ISSUE TITLE
Example-Request: tkDNN YOLOv4 object detection on custom data

### ISSUE THREAD

**Issue by Seioch** [ceccocats/tkDNN#69]
I would love a guide on training your own YOLOv4 detector. Something like taking the weights from a darknet trained detector and connecting it to tkDNN for faster inference.

**Comment by ceccocats** [comment]
Have you tried the exporter?
https://github.com/ceccocats/tkDNN#1export-weights-from-darknet

You just have to run the exporter in your weights and copy the cfg and weights in tkDNN

**Comment by Seioch** [comment]
Yup, though the README wasn't explicit that I had to copy the cfg, weights, and debug files into the yolo4 folder, as well as recompile yolo4.cpp to have the right paths to the cfg and names. Did figure it out in the end though. :)

**Comment by alphapibeta** [comment]
> Yup, though the README wasn't explicit that I had to copy the cfg, weights, and debug files into the yolo4 folder, as well as recompile yolo4.cpp to have the right paths to the cfg and names. Did figure it out in the end though. :)

hope [this](https://github.com/ceccocats/tkDNN/issues/52#issuecomment-662473806) helps anyone whos is looking for to run their custom object detector.
