### ISSUE TITLE
Segmentation fault on test_yolo4tiny

### ISSUE THREAD

**Issue by jerrywgz** [ceccocats/tkDNN#71]
Thanks for your great work! 

Now I want to test yolo4tiny on my own environment. I followed the instruction from document and build successfully. When I tried to run  ```./test_yolo4tiny```, I received segmentation fault in ```configRT = builderRT->createBuilderConfig(); ``` as follows:
![image](https://user-images.githubusercontent.com/22989727/87022917-b5dee780-c209-11ea-9fdd-40b4e9cf488c.png)

My environment is V100 CUDA10.1 CUDNN7.6.5 TensorRT6.01. How can I solve this problem?

**Comment by mive93** [comment]
Hi @jerrywgz,
which GPU or board are you using?

**Comment by jerrywgz** [comment]
> Hi @jerrywgz,
> which GPU or board are you using?

NVIDIA Tesla V100 GPU

**Comment by jerrywgz** [comment]
anyone met such problem? I guess it is caused in createBuilderConfig from TensorRT. Is there something wrong when installing TensorRT?

**Comment by mive93** [comment]
Can you turn on debug please, and copy here that output. Thanks.

```
cmake .. -DDEBUG=True
make
```

**Comment by gabenell** [comment]
I had a segfault at the same place after doing `apt upgrade` recently, which updated some CUDA libs and headers on my Jetson NX. After deleting the previously-generated .rt files from my build directory, the tests worked (as well as my code which uses tkDNN)
