### ISSUE TITLE
About inference with BATCHSIZE > 1

### ISSUE THREAD

**Issue by ferociousricky** [ceccocats/tkDNN#75]
@ceccocats :
Hi I'm Rex. I am having problem with creating the videos "result.avi"(the file size is very small which indicates that the video isn't properly write.), when i set the batch size larger than 1. However, when i set the batchsize = 1 and do the ./demo inference, it can create the result.avi file with the right file size.
Can you help me out or correct my procedure, if i am wrong.
![the_right_size_of_result avi](https://user-images.githubusercontent.com/26264546/87371076-2cd40180-c5b7-11ea-8db8-d011f8e7f2a4.png)
**The right size of the video of "result.avi".**
![the_result avi_is_too_small](https://user-images.githubusercontent.com/26264546/87371078-2e9dc500-c5b7-11ea-842e-d349bd5386f1.png)
**The file is too small!!**

My procedure:
=================================================================================================
1. git clone https://github.com/ceccocats/tkDNN
2. cmake  ../
3. make 
4. git clone https://git.hipert.unimore.it/fgatti/darknet.git # Export weights from darknet.
5. make 
6. mkdir layers debug
7. ./darknet export <path-to-cfg-file> <path-to-weights> layers
8. $export TKDNN_MODE=FP32
9. $export TKDNN_BATCHSIZE=16
10. ./test_yolo4
11. /test_rtinference yolo4_fp32.rt 4
12. ./demo yolo4_fp32.rt ../demo/yolo_test.mp4 y 80 8 0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Thanks,
BR Rex

**Comment by mive93** [comment]
Hi @ferociousricky,
Yes it is correct. In the demo there is an if that let you save the video only for bacth = 1 (line 123 https://github.com/ceccocats/tkDNN/blob/master/demo/demo/demo.cpp).
The code should be changed (not only the if) if you want it to work correctly. However, the output video would be the same wrt the one created with batch=1.

**Comment by ferociousricky** [comment]
@mive93 
Thanks for help and this fantastic project!! :")
