### ISSUE TITLE
compile error！jetson tx2 with jetpack4.2 TensorRT 5.0.6, PLEASE HELP!

### ISSUE THREAD

**Issue by jcyhcs** [ceccocats/tkDNN#88]
![image](https://user-images.githubusercontent.com/34532224/88038679-25919280-cb79-11ea-96cf-b5d1c67c6681.png)

**Comment by ceccocats** [comment]
Hi,
The cmake provided by Ubuntu 18 apt is not sufficient. You need at least cmake 3.15. 
You can either build from source or install with snap
