### ISSUE TITLE
Export weights from darknet if not supported "reorg" layer?

### ISSUE THREAD

**Issue by georgetseng1128** [ceccocats/tkDNN#9]
Hi, we try self darknet model have reorg layer, when execute command ./darknet export xxx.cfg xxx.weight, assert error say not support layer of "reorg", not success create .bin file.

Do you support reorg layer?

**Comment by ceccocats** [comment]
Hello,
Reorg layer does not have weights so you can just skip it.
If you see the code there are already some skipped layers, skip also reorg and you are fine.
Since reorg is not used from yolo3 I haven't seen this error, I will update the darknet repo today.

**Comment by ceccocats** [comment]
https://git.hipert.unimore.it/fgatti/darknet/commit/eb5591ae16c760363a7c3356addb1d0d6ab4f74d
