### ISSUE TITLE
jetson tx2  use yolov4 tensorrt  with demo/yolo_test.mp4,has only 7 fps, is that ok??

### ISSUE THREAD

**Issue by jcyhcs** [ceccocats/tkDNN#91]
jetson tx2 , use tkDNN, jetpack4.2  TensorRT5.0.6, LOOK THE PICTURE:
why slow?

![image](https://user-images.githubusercontent.com/34532224/88143873-8927c880-cc2a-11ea-910c-29431cd16d60.png)

**Comment by mive93** [comment]
Hi @jcyhcs 
It's completely normal, have you checked the results here: https://github.com/ceccocats/tkDNN#results?
If you want to achieve more FPS you can 
- active jetson_clock ( ```sudo jetson_clock``` )
- use FP16 instead of FP32
- use batching

Everything is explained in the README.

**Comment by jcyhcs** [comment]
ok，this picture ， is that mean tx2 fp32 batch 1  is  7.30 fps？ i suggest  you should use " . "point, not use "," comma.
my tx2 already MAXN mode.
my result almost nearly yours. 

![image](https://user-images.githubusercontent.com/34532224/88160484-445b5c00-cc41-11ea-9910-58daac6ddfe6.png)
