### ISSUE TITLE
about yolov4 with channel pruning

### ISSUE THREAD

**Issue by Hipeppa** [ceccocats/tkDNN#92]
when i use yolo4 with channel pruning,it always with question
![Screenshot from 2020-07-24 10-06-55](https://user-images.githubusercontent.com/58104707/88355124-eab87600-cd95-11ea-8cd5-1ba3a2cbb093.png)
![Screenshot from 2020-07-24 10-07-19](https://user-images.githubusercontent.com/58104707/88355130-f441de00-cd95-11ea-9445-d1b039f7a402.png)

**Comment by Hipeppa** [comment]
if i use the cfg produced by the pruned yolov4,it has this problem, if i use the yolo4.cfg, but i modify yolo4.cfg's channels according to the pruned yolo4,it can function properly.

**Comment by ceccocats** [comment]
It can be anche issue of the parser, can you share the exact cfg you are using? Have you tried to run "diff" on the 2 files?

**Comment by Hipeppa** [comment]
[1.txt](https://github.com/ceccocats/tkDNN/files/4970326/1.txt)
[2.txt](https://github.com/ceccocats/tkDNN/files/4970327/2.txt)
the 1.txt that can have problem like the picture, the 2.txt can use normally, but the 2.txt is modify by the 1.txt

**Comment by ceccocats** [comment]
We do not support spaces in the parser
<key>=<value>  is ok
<key> = <value>  is not ok

**Comment by Hipeppa** [comment]
thank u very much，i know .

**Comment by MichaelCong** [comment]
> [1.txt](https://github.com/ceccocats/tkDNN/files/4970326/1.txt)
> [2.txt](https://github.com/ceccocats/tkDNN/files/4970327/2.txt)
> the 1.txt that can have problem like the picture, the 2.txt can use normally, but the 2.txt is modify by the 1.txt

what project do you used for channel pruning?

**Comment by mive93** [comment]
Closing for now, feel free to reopen.

**Comment by Hipeppa** [comment]
> > [1.txt](https://github.com/ceccocats/tkDNN/files/4970326/1.txt)
> > [2.txt](https://github.com/ceccocats/tkDNN/files/4970327/2.txt)
> > the 1.txt that can have problem like the picture, the 2.txt can use normally, but the 2.txt is modify by the 1.txt
> 
> what project do you used for channel pruning?

https://github.com/tanluren/yolov3-channel-and-layer-pruning.git
