### ISSUE TITLE
should it find the obj_class with the max prob?

### ISSUE THREAD

**Issue by zoom1539** [ceccocats/tkDNN#94]
Line 118-123 in src/Yolo3Detection.cpp:
```
        for(int c=0; c<classes; c++) {
            if(dets[j].prob[c] >= confThreshold) {
                obj_class = c;
                prob = dets[j].prob[c];
            }
        }
```
should it find the obj_class with the max prob?

**Comment by ceccocats** [comment]
Actually this is an Error, it should pick all the objects with the prob > confThreshold.
thank you for pointing this
