### ISSUE TITLE
mAP in tkDNN FP32 mode lower than FP16 mode and Darknet

### ISSUE THREAD

**Issue by huyhung411991** [ceccocats/tkDNN#95]
Hi,
I trained different models of Yolov3-tiny and Yolov3-tiny-3l using AlexeyAB's Darknet, used tkDNN to test the mAP in both FP32 and FP16 modes with parsed weights on a customized dataset on Jetson TX2. 

However, in general the mAP in FP32 mode is much lower than I tested in Darknet, and even slightly lower than in FP16, which should be impossible?

Please help.

AP@50:
![Capture](https://user-images.githubusercontent.com/994484/88605874-27e27800-d0b6-11ea-909b-ec34beea8113.PNG)

**Comment by mive93** [comment]
Hi @huyhung411991 
how did you compute the map? 
- with which software
- with which confidence threshold
- on which dataset?

**Comment by huyhung411991** [comment]
My Jetson TX2 currently running JetPack 4.3 with Ubuntu 18.04, CUDA 10.0, cuDNN 7.6.3 and TensorRT 6.0.1.

I tested on a 1000 images of KITTI dataset, with map_points = 101, IoU_thresh = 0.5, conf_thresh = 0.25.

The input sizes for training and testing the models follow the aspect ratios of the original images, for example: 512x160, 640x192, 768x224.

**Comment by huyhung411991** [comment]
I created the rt files and tested with an older commit of tkDNN, also retested with latest commit, but the results have the same issue.

**Comment by lzyang2000** [comment]
I can also confirm it happening with YOLOv4:
Tested on visdrone dataset, 512x512, map_points = 0, IoU_thresh = 0.5, conf_thresh = 0.25.

darknet original: MAP@0.5 IOU: 37.1%, avg precision: 0.62, avg recall: 0.59
darknet tensorRT FP32: MAP@0.5 IOU: 29.7%, avg precision: 0.21, avg recall: 0.37
darknet tensorRT FP16: MAP@0.5 IOU: 29.7%, avg precision: 0.21, avg recall: 0.37

I used a Xavier AGX with JetPack 4.4, CUDA 10.2, TensorRT 7.1.3, cuDNN 8.0.

**Comment by mive93** [comment]
Sorry for the late reply, I didn't see the answer.
The problem is the confidence threshold. You both have to change it in DetectionNN.h. There the conf is 0.3. Try using 0.05 instead and you will get the correct values.

I know, it's hardcoded :/ I have changed it in a branch, but I still have to pull it on the master. 
And yes, FP32 is better than FP16 (but there is no big loss actually) and you don't have to set anything in the demo, just saying which rt you are using.

**Comment by lzyang2000** [comment]
Thanks for the response! Yes I saw the threshold issue and changed the confidence threshold in detectionNN.h to 0.05, and in the demo/config.yaml I set confidence threshold to be 0.25, and got the values that I quote here:

> I can also confirm it happening with YOLOv4:
> Tested on visdrone dataset, 512x512, map_points = 0, IoU_thresh = 0.5, conf_thresh = 0.25.
> 
> darknet original: MAP@0.5 IOU: 37.1%, avg precision: 0.62, avg recall: 0.59
> darknet tensorRT FP32: MAP@0.5 IOU: 29.7%, avg precision: 0.21, avg recall: 0.37
> darknet tensorRT FP16: MAP@0.5 IOU: 29.7%, avg precision: 0.21, avg recall: 0.37
> 
> I used a Xavier AGX with JetPack 4.4, CUDA 10.2, TensorRT 7.1.3, cuDNN 8.0.

If I change the confidence threshold to 0.05 in config.yml, I get 
darknet tensorRT FP32: MAP@0.5 IOU: 33.5%, avg precision: 0.26, avg recall: 0.47
darknet tensorRT FP16: MAP@0.5 IOU: 33.5%, avg precision: 0.26, avg recall: 0.47

I did round the values a bit, but still the performance drop when converting to tensorRT seems strange.

**Comment by lzyang2000** [comment]
One thing I find strange - the visdrone dataset contains 12 labels, namely these:
```
ignored regions
pedestrian
people
bicycle
car
van
truck
tricycle
awning-tricycle
bus
motor
others
```
There are 12 classes in total, but if in config.yaml I change it to 11 classes and set the confidence threshold to 0.05, I can get 36.5% which is somewhat comparable.

My suspicion is that the ignored region class, being the 0th index, affects the calculation of mAP somehow.

**Comment by lzyang2000** [comment]
So I finished testing the pretrained MSCOCO yolov4 weights, and also see a 8.7% decrease from 70% to 61.3% from mAP@0.5IOU.

**Comment by mive93** [comment]
Hi @lzyang2000 

yes, there was a bit loss in tkDNN. I have fixed it. 
See #103

**Comment by lzyang2000** [comment]
Yes I also figured it out yesterday looking at Darknet's code - turns out they are evaluating the mAP at confidence threshold = 0.005, so basically the confidence threshold in DetectionNN.h (I did not pull) and config.yaml need to be at least 0.005.

Now it works. 🤣
