### ISSUE TITLE
Can't find .trt file

### ISSUE THREAD

**Issue by maohu-96** [ceccocats/tkDNN#97]
Hi！ @ceccocats @mive93 
Sorry to disturb you!
I created the build file under tkdnn and copied my cfg and weight files, but the .trt file was not found after make. Is my operation wrong?
![image](https://user-images.githubusercontent.com/63272697/88664602-e2529900-d10f-11ea-9973-cb5165abd698.png)

**Comment by mive93** [comment]
Hi @maohu-96, have you followed the README? 
You should run a test to create a trt model. 
If you're using a model that is not in this repo, you need to first export the weights (https://github.com/ceccocats/tkDNN#1export-weights-from-darknet).
Then you need to create a test similar to this one (https://github.com/ceccocats/tkDNN/blob/master/tests/darknet/yolo4.cpp) and in case, change line 12-19 according to your model.
Finally, you will be able to run the demo, once you have run your test (https://github.com/ceccocats/tkDNN#run-the-demo).

**Comment by maohu-96** [comment]
> Hi @maohu-96, have you followed the README?
> You should run a test to create a trt model.
> If you're using a model that is not in this repo, you need to first export the weights (https://github.com/ceccocats/tkDNN#1export-weights-from-darknet).
> Then you need to create a test similar to this one (https://github.com/ceccocats/tkDNN/blob/master/tests/darknet/yolo4.cpp) and in case, change line 12-19 according to your model.
> Finally, you will be able to run the demo, once you have run your test (https://github.com/ceccocats/tkDNN#run-the-demo).

Thank you very much for your reply! @mive93 
Sorry to disturb you. I exported my model and copied my cfg and names file. An error occurred after make. How can I solve it?
![image](https://user-images.githubusercontent.com/63272697/88774382-f2bd4f00-d1b5-11ea-9d4a-e64f52adc9c7.png)

**Comment by mive93** [comment]
Continued in #98 
Closing for now,
feel free to reopen.
