### ISSUE TITLE
libtkDNN.so error : Undefined reference

### ISSUE THREAD

**Issue by maohu-96** [ceccocats/tkDNN#98]
Hi!
The following error appears after make, what should I do, thank you!
![image](https://user-images.githubusercontent.com/63272697/88752745-410a2800-d18d-11ea-829a-1d7fc78d924d.png)

**Comment by mive93** [comment]
Hi @maohu-96 ,

have you installed yaml-cpp? Which version? 
This the min required version needed: yaml-cpp 0.5.2 (sudo apt install libyaml-cpp-dev)

**Comment by maohu-96** [comment]
> Hi @maohu-96 ,
> 
> have you installed yaml-cpp? Which version?
> This the min required version needed: yaml-cpp 0.5.2 (sudo apt install libyaml-cpp-dev)

Hi @mive93 
Thanks for your reply, I installed yaml-cpp (0.5.2)

**Comment by praveenbadimala** [comment]
libyaml incompatibility with libboost version fix:

a) download libyaml-cpp dev 0.5.2.0 from github
b) change the below import statements wherever it occurs:

#include <boost/utility.hpp>

to

#if BOOST_VERSION >= 106700
#include <boost/next_prior.hpp>
#else
#include <boost/utility.hpp>
#endif

compile the library with the below flags:
cmake and then make and later make install
env CFLAGS='-fPIC' CXXFLAGS='-fPIC' cmake -DCMAKE_BUILD_TYPE=Release ..

then tkdnn compilation should go fine without issue:

Issue references:
https://github.com/jbeder/yaml-cpp/issues/682
https://github.com/arvidn/libtorrent/pull/2929/commits/253ae7ebeaa8287877b7fad2d8b2c083e445340c

**Comment by mive93** [comment]
Closing for now,
feel free to reopen.

**Comment by Goru1890** [comment]
I'm having the same problems as @maohu-96 and I installed the yaml-cpp version 0.5.2-5ubuntu1.
I don't really understand what @praveenbadimala explained above.

**Comment by Goru1890** [comment]
My error is actually a little bit different

![Screenshot from 2020-11-25 10-55-51](https://user-images.githubusercontent.com/35274844/100211865-f2875300-2f0c-11eb-9948-8cf9a5d17f33.png)
